"""empty message

Revision ID: f2d5d8cd3861
Revises: 
Create Date: 2024-01-04 18:29:43.658848

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2d5d8cd3861'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('road_units',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('road_name', sa.String(length=10), nullable=False),
    sa.Column('road_unit_head', sa.String(length=10), nullable=False),
    sa.Column('road_unit_tail', sa.String(length=10), nullable=False),
    sa.Column('orientation', sa.String(length=10), nullable=False),
    sa.Column('action', sa.String(length=10), nullable=False),
    sa.Column('distence', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('road_units')
    # ### end Alembic commands ###
